# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 646)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 127);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(520, 260, 221, 31))
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(520, 320, 221, 31))
        self.passwordInput.setObjectName("passwordInput")
        self.UsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(220, 260, 251, 31))
        self.UsernameLabel.setStyleSheet("color: rgb(0, 85, 255);\n"
"font-size: 28px;")
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.PasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.PasswordLabel.setGeometry(QtCore.QRect(410, 310, 71, 41))
        self.PasswordLabel.setStyleSheet("color: rgb(0, 85, 255);\n"
"font-size: 28px;r")
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.DontHaveAccountLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.DontHaveAccountLabel1.setGeometry(QtCore.QRect(350, 470, 91, 16))
        self.DontHaveAccountLabel1.setObjectName("DontHaveAccountLabel1")
        self.SignUpDirectionLabel = QtWidgets.QLabel(self.centralwidget)
        self.SignUpDirectionLabel.setGeometry(QtCore.QRect(440, 470, 41, 16))
        self.SignUpDirectionLabel.setStyleSheet("color: rgb(0, 85, 255);\n"
"text-decoration: underline;")
        self.SignUpDirectionLabel.setObjectName("SignUpDirectionLabel")
        self.DontHaveAccountLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.DontHaveAccountLabel2.setGeometry(QtCore.QRect(480, 470, 121, 16))
        self.DontHaveAccountLabel2.setObjectName("DontHaveAccountLabel2")
        self.LoginScreenLabel = QtWidgets.QLabel(self.centralwidget)
        self.LoginScreenLabel.setGeometry(QtCore.QRect(350, 110, 241, 91))
        self.LoginScreenLabel.setStyleSheet("color: rgb(0, 85, 255);\n"
"font-size: 48px;")
        self.LoginScreenLabel.setObjectName("LoginScreenLabel")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(630, 390, 111, 31))
        self.LoginButton.setStyleSheet("font-size: 20px;\n"
"border: 2px solid #000000;\n"
"border-radius: 8px;\n"
"color: rgb(0, 85, 255);\n"
"background-color: rgb(223, 255, 10);")
        self.LoginButton.setObjectName("LoginButton")
        self.LoginButton.clicked.connect(self.login())
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LoginScreen"))
        self.UsernameLabel.setText(_translate("MainWindow", "Kullanıcı Adı / Email:"))
        self.PasswordLabel.setText(_translate("MainWindow", "Şifre:"))
        self.DontHaveAccountLabel1.setText(_translate("MainWindow", "Hesabınız yok mu? "))
        self.SignUpDirectionLabel.setText(_translate("MainWindow", "Buraya"))
        self.DontHaveAccountLabel2.setText(_translate("MainWindow", "tıklayıp kayıt olabilirsiniz."))
        self.LoginScreenLabel.setText(_translate("MainWindow", "Giriş Ekranı"))
        self.LoginButton.setText(_translate("MainWindow", "Giriş"))

    def login(self):
        email = self.usernameInput.text()
        password = self.passwordInput.text()
        print("done")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
