# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'invitation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvitationFrame(object):
    def setupUi(self, InvitationFrame):
        InvitationFrame.setObjectName("InvitationFrame")
        InvitationFrame.resize(265, 72)
        InvitationFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.FromLabel = QtWidgets.QLabel(InvitationFrame)
        self.FromLabel.setGeometry(QtCore.QRect(20, 10, 141, 21))
        self.FromLabel.setObjectName("FromLabel")
        self.DetailsLabel = QtWidgets.QLabel(InvitationFrame)
        self.DetailsLabel.setGeometry(QtCore.QRect(20, 30, 151, 41))
        self.DetailsLabel.setWordWrap(True)
        self.DetailsLabel.setObjectName("DetailsLabel")
        self.line_7 = QtWidgets.QFrame(InvitationFrame)
        self.line_7.setGeometry(QtCore.QRect(0, 70, 269, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.AcceptButton = QtWidgets.QPushButton(InvitationFrame)
        self.AcceptButton.setGeometry(QtCore.QRect(170, 10, 75, 23))
        self.AcceptButton.setObjectName("AcceptButton")
        self.RejectButton = QtWidgets.QPushButton(InvitationFrame)
        self.RejectButton.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.RejectButton.setObjectName("RejectButton")

        self.retranslateUi(InvitationFrame)
        QtCore.QMetaObject.connectSlotsByName(InvitationFrame)

    def retranslateUi(self, InvitationFrame):
        _translate = QtCore.QCoreApplication.translate
        InvitationFrame.setWindowTitle(_translate("InvitationFrame", "Frame"))
        self.FromLabel.setText(_translate("InvitationFrame", "Kimden: Kral"))
        self.DetailsLabel.setText(_translate("InvitationFrame", "Açıklama: Gel bakalım."))
        self.AcceptButton.setText(_translate("InvitationFrame", "Kabul Et"))
        self.RejectButton.setText(_translate("InvitationFrame", "Reddet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InvitationFrame = QtWidgets.QFrame()
    ui = Ui_InvitationFrame()
    ui.setupUi(InvitationFrame)
    InvitationFrame.show()
    sys.exit(app.exec_())
