# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\canoz\Desktop\taskDev.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from functions.openURLs import openURLs
from functions.uploadFile import uploadFile


class Ui_TaskDevFrame(object):
    def upload(self, task, storage, db):
        self.UploadedFilesLabel.setVisible(False)
        self.StatusLabel.setText("Durum: Yükleniyor...")
        result = uploadFile(task, storage, db)

        if result:
            self.StatusLabel.setText("Durum: " + result["TaskStatus"])
            self.UploadedFilesLabel.setVisible(True)
            self.UploadedFilesLabel.mousePressEvent = lambda x: openURLs(result["TaskFileURLs"])        

    def setupUi(self, TaskDevFrame, task, storage, db):
        TaskDevFrame.setObjectName("TaskDevFrame")
        TaskDevFrame.setStyleSheet("background-color: rgb(255, 255, 127);")

        self.line_5 = QtWidgets.QFrame(TaskDevFrame)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 399, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.FromLabel = QtWidgets.QLabel(TaskDevFrame)
        self.FromLabel.setGeometry(QtCore.QRect(10, 0, 191, 21))
        self.FromLabel.setObjectName("FromLabel")
        
        self.UploadFileButton = QtWidgets.QPushButton(TaskDevFrame)
        self.UploadFileButton.setGeometry(QtCore.QRect(270, 10, 101, 23))
        self.UploadFileButton.setStyleSheet("background-color: rgb(230, 230, 250);")
        self.UploadFileButton.setObjectName("UploadFileButton")
        self.UploadFileButton.clicked.connect(lambda: self.upload(task, storage, db))

        self.StatusLabel = QtWidgets.QLabel(TaskDevFrame)
        self.StatusLabel.setGeometry(QtCore.QRect(270, 40, 101, 16))
        self.StatusLabel.setObjectName("StatusLabel")

        self.DeadlineLabel = QtWidgets.QLabel(TaskDevFrame)
        self.DeadlineLabel.setGeometry(QtCore.QRect(10, 60, 151, 16))
        self.DeadlineLabel.setObjectName("DeadlineLabel")

        self.UploadedFilesLabel = QtWidgets.QLabel(TaskDevFrame)
        self.UploadedFilesLabel.setGeometry(QtCore.QRect(260, 60, 111, 16))
        self.UploadedFilesLabel.setStyleSheet("text-decoration: underline;\n"
"color: rgb(0, 80, 255);")
        self.UploadedFilesLabel.setCursor(QtCore.Qt.PointingHandCursor)
        self.UploadedFilesLabel.setObjectName("UploadedFilesLabel")
        if task["TaskStatus"] == "Bekleniyor":
            self.UploadedFilesLabel.setVisible(False)
        else:
            self.UploadedFilesLabel.mousePressEvent = lambda x: openURLs(task["TaskFileURLs"])

        self.DetailsLabel = QtWidgets.QLabel(TaskDevFrame)
        self.DetailsLabel.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.DetailsLabel.setWordWrap(True)
        self.DetailsLabel.setObjectName("DetailsLabel")

        self.retranslateUi(TaskDevFrame, task)
        QtCore.QMetaObject.connectSlotsByName(TaskDevFrame)

    def retranslateUi(self, TaskDevFrame, task):
        _translate = QtCore.QCoreApplication.translate
        TaskDevFrame.setWindowTitle(_translate("TaskDevFrame", "Frame"))
        self.FromLabel.setText(_translate("TaskDevFrame", " Kimden: " + task["From"]))
        self.UploadFileButton.setText(_translate("TaskDevFrame", "Dosya Yükle..."))
        self.StatusLabel.setText(_translate("TaskDevFrame", "Durum: " + task["TaskStatus"]))
        self.DeadlineLabel.setText(_translate("TaskDevFrame", "Son Teslim Tarihi: " + task["TaskDeadline"]))
        self.UploadedFilesLabel.setText(_translate("TaskDevFrame", "Yüklenen Dosyaları Gör"))
        self.DetailsLabel.setText(_translate("TaskDevFrame", " Açıklama: " + task["TaskDetails"]))
