# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserFrame(object):
    def setupUi(self, UserFrame):
        UserFrame.setObjectName("UserFrame")
        UserFrame.resize(299, 42)
        UserFrame.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.UserLabel = QtWidgets.QLabel(UserFrame)
        self.UserLabel.setGeometry(QtCore.QRect(20, 10, 151, 21))
        self.UserLabel.setObjectName("UserLabel")
        self.GiveTaskButton = QtWidgets.QPushButton(UserFrame)
        self.GiveTaskButton.setGeometry(QtCore.QRect(200, 10, 75, 23))
        self.GiveTaskButton.setStyleSheet("background-color: rgb(187, 227, 89);")
        self.GiveTaskButton.setObjectName("GiveTaskButton")
        self.line_2 = QtWidgets.QFrame(UserFrame)
        self.line_2.setGeometry(QtCore.QRect(0, 40, 299, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(UserFrame)
        QtCore.QMetaObject.connectSlotsByName(UserFrame)

    def retranslateUi(self, UserFrame):
        _translate = QtCore.QCoreApplication.translate
        UserFrame.setWindowTitle(_translate("UserFrame", "Frame"))
        self.UserLabel.setText(_translate("UserFrame", "Kullanıcı: Kullanici1"))
        self.GiveTaskButton.setText(_translate("UserFrame", "Görev Ver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserFrame = QtWidgets.QFrame()
    ui = Ui_UserFrame()
    ui.setupUi(UserFrame)
    UserFrame.show()
    sys.exit(app.exec_())
