# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\canoz\Desktop\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, MainWindow, userInfo):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 127);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.ProfileTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProfileTextLabel.setGeometry(QtCore.QRect(100, 40, 151, 21))
        self.ProfileTextLabel.setObjectName("ProfileTextLabel")

        self.TaskerrLabel = QtWidgets.QLabel(self.centralwidget)
        self.TaskerrLabel.setGeometry(QtCore.QRect(470, 30, 231, 51))
        self.TaskerrLabel.setStyleSheet("font-size: 48px;")
        self.TaskerrLabel.setObjectName("TaskerrLabel")

        self.ProfileLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProfileLabel.setGeometry(QtCore.QRect(40, 30, 51, 51))
        self.ProfileLabel.setText("")
        self.ProfileLabel.setPixmap(QtGui.QPixmap("src/img/profile.png"))
        self.ProfileLabel.setObjectName("ProfileLabel")

        self.VersionLabel = QtWidgets.QLabel(self.centralwidget)
        self.VersionLabel.setGeometry(QtCore.QRect(710, 50, 61, 31))
        self.VersionLabel.setStyleSheet("font-size: 24px;")
        self.VersionLabel.setObjectName("VersionLabel")

        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(110, 180, 161, 21))
        self.UsernameInput.setObjectName("UsernameInput")

        self.InviteUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.InviteUserButton.setGeometry(QtCore.QRect(280, 200, 101, 21))
        self.InviteUserButton.setStyleSheet("background-color: rgb(180, 230, 200);")
        self.InviteUserButton.setObjectName("InviteUserButton")

        self.UsersLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.UsersLayoutWidget.setGeometry(QtCore.QRect(30, 270, 301, 291))
        self.UsersLayoutWidget.setObjectName("UsersLayoutWidget")
        self.UsersLayout = QtWidgets.QVBoxLayout(self.UsersLayoutWidget)
        self.UsersLayout.setContentsMargins(0, 0, 0, 0)
        self.UsersLayout.setObjectName("UsersLayout")

        self.UsersLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsersLabel.setGeometry(QtCore.QRect(110, 130, 141, 31))
        self.UsersLabel.setStyleSheet("font-size: 28px;\n"
"color: rgb(0, 80, 255)")
        self.UsersLabel.setObjectName("UsersLabel")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(400, 100, 16, 471))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.ActiveTasksLabel = QtWidgets.QLabel(self.centralwidget)
        self.ActiveTasksLabel.setGeometry(QtCore.QRect(530, 130, 181, 31))
        self.ActiveTasksLabel.setStyleSheet("font-size: 28px;\n"
"color: rgb(0, 80, 255)")
        self.ActiveTasksLabel.setObjectName("ActiveTasksLabel")

        self.ActiveTasksLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.ActiveTasksLayoutWidget.setGeometry(QtCore.QRect(440, 190, 331, 371))
        self.ActiveTasksLayoutWidget.setObjectName("ActiveTasksLayoutWidget")
        self.ActiveTasksLayout = QtWidgets.QVBoxLayout(self.ActiveTasksLayoutWidget)
        self.ActiveTasksLayout.setContentsMargins(0, 0, 0, 0)
        self.ActiveTasksLayout.setObjectName("ActiveTasksLayout")

        self.DetailsInput = QtWidgets.QTextEdit(self.centralwidget)
        self.DetailsInput.setGeometry(QtCore.QRect(110, 210, 161, 41))
        self.DetailsInput.setObjectName("DetailsInput")

        self.UsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(40, 180, 61, 16))
        self.UsernameLabel.setObjectName("UsernameLabel")

        self.DetailsLabel = QtWidgets.QLabel(self.centralwidget)
        self.DetailsLabel.setGeometry(QtCore.QRect(50, 220, 51, 16))
        self.DetailsLabel.setObjectName("DetailsLabel")

        self.InvitationSentText = QtWidgets.QLabel(self.centralwidget)
        self.InvitationSentText.setGeometry(QtCore.QRect(290, 230, 81, 16))
        self.InvitationSentText.setStyleSheet("color: rgb(0, 255, 0)")
        self.InvitationSentText.setObjectName("InvitationSentText")
        self.InvitationSentText.setVisible(False)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow, userInfo["Username"])
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, username):
        print(username)
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ProfileTextLabel.setText(_translate("MainWindow", "Hoşgeldiniz, " + username))
        self.TaskerrLabel.setText(_translate("MainWindow", "𝓣𝓪𝓼𝓴𝓮𝓻𝓻"))
        self.VersionLabel.setText(_translate("MainWindow", "v0.1"))
        self.InviteUserButton.setText(_translate("MainWindow", "Kullanıcıyı Davet Et"))
        self.UsersLabel.setText(_translate("MainWindow", "Kullanıcılar"))
        self.ActiveTasksLabel.setText(_translate("MainWindow", "Aktif Görevler"))
        self.UsernameLabel.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.DetailsLabel.setText(_translate("MainWindow", "Açıklama:"))
        self.InvitationSentText.setText(_translate("MainWindow", "Davet Gönderildi!"))