# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\canoz\Downloads\kayt_ekran_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import json
from PyQt5 import QtCore, QtGui, QtWidgets
from pyrebase.pyrebase import Auth, Database
from requests.models import HTTPError

class Ui_SignUpWindow(object):
    def setupUi(self, MainWindow, auth: Auth, db: Database):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(255, 255, 127);")
        MainWindow.setIconSize(QtCore.QSize(24, 24))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.EnterEmailLabel = QtWidgets.QLabel(self.centralwidget)
        self.EnterEmailLabel.setGeometry(QtCore.QRect(150, 120, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.EnterEmailLabel.setFont(font)
        self.EnterEmailLabel.setStyleSheet("color: rgb(0, 0, 255);")
        self.EnterEmailLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EnterEmailLabel.setObjectName("EnterEmailLabel")

        self.UsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(140, 210, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setStyleSheet("color: rgb(0, 0, 255);")
        self.UsernameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.UsernameLabel.setObjectName("UsernameLabel")

        self.PasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.PasswordLabel.setGeometry(QtCore.QRect(190, 300, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setStyleSheet("color: rgb(0, 0, 255);")
        self.PasswordLabel.setLineWidth(1)
        self.PasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordLabel.setObjectName("PasswordLabel")
        
        self.SignUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.SignUpButton.setEnabled(True)
        self.SignUpButton.setGeometry(QtCore.QRect(670, 517, 93, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignUpButton.sizePolicy().hasHeightForWidth())
        self.SignUpButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.SignUpButton.setFont(font)
        self.SignUpButton.setAutoFillBackground(False)
        self.SignUpButton.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.SignUpButton.setDefault(False)
        self.SignUpButton.setObjectName("SignUpButton")
        self.SignUpButton.clicked.connect(lambda: self.signUp(auth, db))

        self.PasswordAgainLabel = QtWidgets.QLabel(self.centralwidget)
        self.PasswordAgainLabel.setGeometry(QtCore.QRect(130, 390, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PasswordAgainLabel.setFont(font)
        self.PasswordAgainLabel.setStyleSheet("color: rgb(0, 0, 255);")
        self.PasswordAgainLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordAgainLabel.setObjectName("PasswordAgainLabel")
        
        self.Header = QtWidgets.QLabel(self.centralwidget)
        self.Header.setGeometry(QtCore.QRect(250, 40, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Header.setFont(font)
        self.Header.setStyleSheet("color: rgb(0, 0, 255);")
        self.Header.setAlignment(QtCore.Qt.AlignCenter)
        self.Header.setObjectName("Header")

        self.AdminCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.AdminCheckbox.setGeometry(QtCore.QRect(590, 520, 81, 20))
        self.AdminCheckbox.setObjectName("AdminCheckbox")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 520, 181, 20))
        self.label_6.setObjectName("label_6")

        self.EmailInput = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailInput.setGeometry(QtCore.QRect(300, 131, 231, 31))
        self.EmailInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.EmailInput.setObjectName("EmailInput")
        self.EmailInput.textChanged.connect(self.updateUsernameInput)

        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(302, 220, 231, 31))
        self.UsernameInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UsernameInput.setReadOnly(True)
        self.UsernameInput.setObjectName("UsernameInput")

        self.PasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordInput.setGeometry(QtCore.QRect(300, 310, 231, 31))
        self.PasswordInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordInput.setObjectName("PasswordInput")

        self.PasswordAgainInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordAgainInput.setGeometry(QtCore.QRect(300, 400, 231, 31))
        self.PasswordAgainInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PasswordAgainInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordAgainInput.setObjectName("PasswordAgainInput")

        self.InvalidEmail = QtWidgets.QLabel(self.centralwidget)
        self.InvalidEmail.setGeometry(QtCore.QRect(540, 140, 141, 16))
        self.InvalidEmail.setStyleSheet("color: rgb(255, 0, 0);")
        self.InvalidEmail.setObjectName("InvalidEmail")
        self.InvalidEmail.setVisible(False)

        self.InvalidPassword1 = QtWidgets.QLabel(self.centralwidget)
        self.InvalidPassword1.setGeometry(QtCore.QRect(540, 320, 141, 16))
        self.InvalidPassword1.setStyleSheet("color: rgb(255, 0, 0);")
        self.InvalidPassword1.setObjectName("InvalidPassword1")
        self.InvalidPassword1.setVisible(False)

        self.InvalidPassword2 = QtWidgets.QLabel(self.centralwidget)
        self.InvalidPassword2.setGeometry(QtCore.QRect(540, 410, 141, 16))
        self.InvalidPassword2.setStyleSheet("color: rgb(255, 0, 0);")
        self.InvalidPassword2.setObjectName("InvalidPassword2")
        self.InvalidPassword2.setVisible(False)

        self.ErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.ErrorLabel.setGeometry(QtCore.QRect(390, 462, 371, 31))
        self.ErrorLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.ErrorLabel.setWordWrap(True)
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.ErrorLabel.setVisible(False)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign Up"))
        self.EnterEmailLabel.setText(_translate("MainWindow", "E-mail gir:"))
        self.UsernameLabel.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.PasswordLabel.setText(_translate("MainWindow", "Şifre:"))
        self.SignUpButton.setText(_translate("MainWindow", "Onayla"))
        self.PasswordAgainLabel.setText(_translate("MainWindow", "Şifre Tekrardan:"))
        self.Header.setText(_translate("MainWindow", "Kullanıcı Kayıt Ekranı"))
        self.AdminCheckbox.setText(_translate("MainWindow", "Yönetici"))
        self.label_6.setText(_translate("MainWindow", "Yönetici olmak için işaretleyiniz:"))
        self.InvalidEmail.setText(_translate("MainWindow", "Geçersiz Email!"))
        self.InvalidPassword1.setText(_translate("MainWindow", "Geçersiz Şifre!"))
        self.InvalidPassword2.setText(_translate("MainWindow", "Şifreler Eşleşmiyor!"))
        self.ErrorLabel.setText(_translate("MainWindow", "Hata: "))


    def updateUsernameInput(self, username: str):
        self.UsernameInput.setText(username.split("@")[0])

    def signUp(self, auth: Auth, db: Database):
        email = self.EmailInput.text()
        username = self.UsernameInput.text()
        password = self.PasswordInput.text()
        passwordConfirm = self.PasswordAgainInput.text()
        isAdmin = self.AdminCheckbox.isChecked()
        if "@gmail.com" not in email:
            self.InvalidEmail.setVisible(True)
        elif not password:
            self.InvalidEmail.setVisible(False)
            self.InvalidPassword1.setVisible(True)
        elif not password == passwordConfirm:
            self.InvalidEmail.setVisible(False)
            self.InvalidPassword1.setVisible(False)
            self.InvalidPassword2.setVisible(True)
        else:
            try:
                auth.create_user_with_email_and_password(email, password)
                document = db.collection("users").document(username)
                document.set({
                    "Email" : email,
                    "Username": username,
                    "Password": password,
                    "Admin": isAdmin,
                    "CompletedTaskAmount": 0,
                    "Tasks": [],
                    "Users": [],
                    "Invitations": [],
                })
                self.ErrorLabel.setStyleSheet("color: rgb(0, 255, 0);")
                self.ErrorLabel.setText("Hesabınız başarıyla oluşturuldu, şimdi giriş yapabilirsiniz.")
                self.ErrorLabel.setVisible(True)
                self.InvalidEmail.setVisible(False)
                self.InvalidPassword1.setVisible(False)
                self.InvalidPassword2.setVisible(False)
                self.showPopup(email, username, password)
            except HTTPError as e:
                self.InvalidEmail.setVisible(False)
                self.InvalidPassword1.setVisible(False)
                self.InvalidPassword2.setVisible(False)
                self.ErrorLabel.setText("Hata: " + json.loads(e.args[1])["error"]["message"])
                self.ErrorLabel.setStyleSheet("color: rgb(255, 0, 0);")
                self.ErrorLabel.setVisible(True)

    def showPopup(self, email, username, password):
        msg = QtWidgets.QMessageBox()
        msg.resize(200, 150)
        msg.setWindowTitle("Success!")
        msg.setStyleSheet("background-color: rgb(255, 255, 127);")
        msg.setText("Hesap Basariyla Olustuldu!")
        msg.setStandardButtons(QtWidgets.QMessageBox.Close)
        msg.setDetailedText("Eposta: " + email + "\nKullanıcı Adı: " + username + "\nŞifre: " + password)
        msg.exec()